import smtplib
import logger

from email.MIMEMultipart import MIMEMultipart
from email.MIMEText import MIMEText
from email.Utils import COMMASPACE, formatdate
from config import CONFIG

def send_mail(body, subject, recipients, **kwargs):
    sender = CONFIG.MAIL_SEND_FROM

    msg = MIMEMultipart()
    msg['From'] = sender
    msg['To'] = COMMASPACE.join(recipients)
    msg['Date'] = formatdate(localtime=True)
    msg['Subject'] = subject

    try:
        msg.attach(MIMEText(body))
        smtpObj = smtplib.SMTP()
        smtpObj.connect()
        smtpObj.sendmail(sender, recipients, msg.as_string())
        smtpObj.close()
    except Exception as e:
        print "Error: unable to send email", e.__class__, e.message


def send_mail_approve(record_id):
    body = """Dear XSDB approver,

A new entry is requested for insert into XSDB. Please review this new request at your earliest convenience at the following link.

{edit_page_url}{record_id}

Automated response generated by XSDB tool. Please do not send email response to this email.
    """.format(edit_page_url=CONFIG.EDIT_PAGE_URL, record_id=record_id)

    subject = "XSDB new record for approval"

    send_mail(body, subject, CONFIG.GROUP_MAILS[1:])
