export const recordList = [
    {
        "DAS": "DASs",
        "MCM": "MCMm",
        "accuracy": "accuracycc",
        "comments": "Comm",
        "contact": "Section_test",
        "cross_section": "Section_test",
        "cuts": "cuttts",
        "energy": "Section_test",
        "equivalent_lumi": "Section_test",
        "fraction_negative_weight": "Section_test",
        "id": "595f621642cdba7425ded7d9",
        "kFactor": "Section_test",
        "matrix_generator": "Section_test",
        "other_uncertainty": "otherunnn",
        "process_name": "process2",
        "refs": "refss",
        "reweighting": "Section_test",
        "shower": "Section_test",
        "total_uncertainty": "Section_test"
    },
    {
        "DAS": "DASs",
        "MCM": "MCMm",
        "accuracy": "accuracycc",
        "comments": "Comm",
        "contact": "Section_test",
        "cross_section": "Section_test",
        "cuts": "cuttts",
        "energy": "Section_test",
        "equivalent_lumi": "Section_test",
        "fraction_negative_weight": "Section_test",
        "id": "595f621642cdba7425ded7d9",
        "kFactor": "Section_test",
        "matrix_generator": "Section_test",
        "other_uncertainty": "otherunnn",
        "process_name": "process2",
        "refs": "refss",
        "reweighting": "Section_test",
        "shower": "Section_test",
        "total_uncertainty": "Section_test"
    },
    {
        "DAS": "DASs",
        "MCM": "MCMm",
        "accuracy": "accuracycc",
        "comments": "Comm",
        "contact": "Section_test",
        "cross_section": "Section_test",
        "cuts": "cuttts",
        "energy": "Section_test",
        "equivalent_lumi": "Section_test",
        "fraction_negative_weight": "Section_test",
        "id": "595f621642cdba7425ded7d9",
        "kFactor": "Section_test",
        "matrix_generator": "Section_test",
        "other_uncertainty": "otherunnn",
        "process_name": "process2",
        "refs": "refss",
        "reweighting": "Section_test",
        "shower": "Section_test",
        "total_uncertainty": "Section_test"
    }
]